# Generated by Django 4.2.2 on 2023-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField(max_length=7)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
