# Generated by Django 4.2.2 on 2023-06-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=500),
        ),
    ]
